### PR TITLE
refresh list of available classes and fix bond issue

### PR DESCRIPTION
**Pull request by bit-pirate**
This is an example of implementing a solution for #17.

I'm not too familiar with boost::function and boost::bind and not sure, if the below is best way to implement this. I basically just followed the existing style.

Please feel free to suggest better ways of implementing this - or add your own solution. :-)

PS: This is an important new feature addition, but does not change the API. Will it be possible to add this to Inidgo?

### CODE REVIEW

**Comment by bit-pirate** [comment]
Second commit has been added for the bond breakage problem #19.

**Comment by dirk-thomas** [comment]
+1 to merge this but to a (to be created) indigo-devel branch.

**Comment by dirk-thomas** [comment]
Please update the package.xml to include the minimum version dependency on pluginlib to be (the to be released) 1.10.0. Depends on ros/pluginlib#24.

**Comment by bit-pirate** [comment]
Closing this in favour of PR #20 .

**Pull request closed without merging**
