### PR TITLE
refresh list of available classes and fix bond issue

### PR DESCRIPTION
**Pull request by bit-pirate**
This contains the same changes as PR #18 but for indigo-devel.

### CODE REVIEW

**Comment by bit-pirate** [comment]
Since the changes in this PR are not changing the API. Would it be possible to back-port this to hyrdo-devel as well and release it?

**Comment by esteve** [comment]
Thanks!

**Comment by bit-pirate** [comment]
@esteve will this be released into hydro as well? Would be nice.

**Comment by esteve** [comment]
@bit-pirate Done, I just backported this to the hydro-devel branch, sorry for the delay.

**Pull request merged**
